### PR TITLE
Make it possible to build with cmake

### PR DESCRIPTION
**Pull request by sharkwouter**
CMake is nice, because it allows for easier installation and it also builds some of the additional files like SDL2main, sdl2-config and the sdl2.pc file. ~~I still need to make it so the output of ``sdl2-config --libs`` makes sense, which is why this is still WIP~~. Everything ~~else~~ should ~~already~~ work like expected, so help with testing would be greatly appreciated. Building and installing with cmake can be done in the following way:
```
mkdir build
cd build
psp-cmake ..
make
make install
```

### CODE REVIEW

**Comment by sharkwouter** [comment]
The issues when building mentioned in earlier comments have been resolved now.

**Comment by sharkwouter** [comment]
I'm really close to being able to ship this now. All the variables required to make sdl2-config and sdl2.pc work are now there, but for some reason it's reordering the EXTRA_LIBS list. This still prevents you from building with sdl2-config and pkgconf. Will look into this later.

**Comment by sharkwouter** [comment]
Okay, the final issues was solved and sdl2-config and the pc file should be good now. I've tested building my test application with ``psp-gcc main.c $($PSPDEV/psp/bin/sdl2-config --cflags) $($PSPDEV/psp/bin/sdl2-config --libs)`` after installing this and it worked fine. Please review this PR.

**Comment by sharkwouter** [comment]
To give a bit more background for anyone who'd like to review this. The changes to the following files do not affect what was previously there in any way (although they might affect building for other systems than the PSP if there is an error, but that is unlikely), but do enable cmake to work:
- include/SDL_config.h.cmake 
- CMakeLists.txt

The rest of the changes are there to prevent warnings from interrupting the build with cmake. The exception to this is renaming ``SDL_TIMERS_PSP`` to ``SDL_TIMER_PSP``, which was done for consistency in the configuration. If any of these changes affect the result of the code, that is a bug.

**Comment by sharkwouter** [comment]
Is there still anything which needs to be addressed with this PR?

**Comment by joel16** [comment]
No there isn't. I believe I was waiting on what other thought about it this but it seems like there's nothing so I'll go ahead and merge this.

**Pull request merged**
