### PR TITLE
Add makefile for SDL2main

### PR DESCRIPTION
**Pull request by sharkwouter**
This was made by @dbeef while working on getting SDL2 in the into the
psp toolchain.

### CODE REVIEW

**Comment by dbeef** [comment]
Yeah, so as I understand, this `include $(PSPSDK)/lib/build.mak` allows only one library target for a single makefile - correct me if I am wrong. That's why I created a separate makefile specifically for this libSDL2main target.

**Comment by sharkwouter** [comment]
I did some testing and I got a simple game I started working on a while ago working on psp using this:
JPEG_20200502_164357

The is the code I used:
https://github.com/sharkwouter/jewelpop/blob/a4608e0b661ecc341b306739998ca5748a8bcb13/src/main.cpp#L30-L41

**Comment by sharkwouter** [comment]
I just accidentally pushed come commits which remove unused libraries which were linked from in the main makefile to this branch. I'll move them to a different branch.

**Comment by sharkwouter** [comment]
Okay, the changes to the other makefile have been reverted now.

**Pull request merged**
